[package]
name = "nebula"
type = "contract"
version = "0.1.0"
authors = [""]

[dependencies]
authwit = { git = "https://github.com/AztecProtocol/aztec-nr", tag = "master" , directory = "authwit" }
aztec = { git = "https://github.com/AztecProtocol/aztec-nr", tag = "master" , directory = "aztec" }
compressed_string = {git="https://github.com/AztecProtocol/aztec-nr/", tag="master", directory="compressed-string"}
uint_note = {git="https://github.com/AztecProtocol/aztec-nr/", tag="master", directory="uint-note"}